version: '3'
services:
  sec-db:
    image: 'mysql:5.6'
    ports:
      - '3307:3306'
    volumes:
      - './data/mysql:/var/lib/mysql'
    env_file:
      - ./config/mysql.env

  sec-service:
    depends_on:
      - sec-db
    build:
      context: ../app-sec-rest-api
    ports:
      - '8087:8080'
    volumes:
      - '../app-sec-rest-api:/home/java/app'
    env_file:
      - ./config/mysql.env
      - ./config/spring-api.env
